// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN-jsgAP44SPwj2kvmK4FbTLNerJKyh3M',
    appId: '1:852362003678:web:e7f9534447be0688ecae4f',
    messagingSenderId: '852362003678',
    projectId: 'athletiq-app-40d8e',
    authDomain: 'athletiq-app-40d8e.firebaseapp.com',
    storageBucket: 'athletiq-app-40d8e.appspot.com',
    measurementId: 'G-ZHYWWV7XJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQqac0NQBypauNUofglpm2t1DRsRMjHg',
    appId: '1:852362003678:android:d0ab3b86d8261d11ecae4f',
    messagingSenderId: '852362003678',
    projectId: 'athletiq-app-40d8e',
    storageBucket: 'athletiq-app-40d8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTtVwAysy2P4sMGkTfHXjFOTmkbq0W48',
    appId: '1:852362003678:ios:2fe94e80dc7b07b9ecae4f',
    messagingSenderId: '852362003678',
    projectId: 'athletiq-app-40d8e',
    storageBucket: 'athletiq-app-40d8e.appspot.com',
    iosBundleId: 'com.example.athletiqapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjTtVwAysy2P4sMGkTfHXjFOTmkbq0W48',
    appId: '1:852362003678:ios:2fe94e80dc7b07b9ecae4f',
    messagingSenderId: '852362003678',
    projectId: 'athletiq-app-40d8e',
    storageBucket: 'athletiq-app-40d8e.appspot.com',
    iosBundleId: 'com.example.athletiqapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN-jsgAP44SPwj2kvmK4FbTLNerJKyh3M',
    appId: '1:852362003678:web:20f37399ad18425decae4f',
    messagingSenderId: '852362003678',
    projectId: 'athletiq-app-40d8e',
    authDomain: 'athletiq-app-40d8e.firebaseapp.com',
    storageBucket: 'athletiq-app-40d8e.appspot.com',
    measurementId: 'G-6C4PLK01E3',
  );
}
